#ifndef TUI_H
#define TUI_H

#include <xmlreader.h>
#include "cocos2d.h"
USING_NS_CC;

#include <vector>
using std::vector;
#include <string>
using std::string;
#include <map>
using std::map;
using std::pair;

typedef vector<string> TuiEventIDVector;
typedef map<string, CCNode*> TuiControlDictionary;

/**
 @class Tui
 @brief Tui extends from CCLayer, a movieclip panel is a Tui, a Tui 
 		includes some images, buttons and so on, Tui is created by parse 
		tui xml file. tui xml is generated by flash cs extension TGameUITool.
 */
class TuiManager;
class Tui : public CCLayer
{
public:
	Tui( TuiManager* uimanager, const char* name );
	virtual ~Tui();

	static Tui *create( TuiManager* uimanager, const char* name );
	bool init();

	virtual void onEnter();
	virtual void onExit();
public:

	TuiManager* tuiManager() { return ui_manager; }

	const char* name(){ return tui_name; }
	CCNode* getControl( const char* key );
	void registerListener();
	void unregisterListener();

public:
	void onButtonClick( CCObject* o );

private:
	CCMenu* menu_group;
	TuiManager* ui_manager;
	char tui_name[64];
	TuiEventIDVector vec_event;
	TuiControlDictionary dict_control;

	friend class TuiManager;
};

#endif //TUI_H
