PATH_WELCOMEUI = "tui/tui_welcomeui.xml"

Tag_welcomeui = { 

PANEL_WELCOME = 1 ,
IMG_BG = 2 ,
BTN_OK = 3 ,
CTLV_LEFT = 4 ,
ARMBTN_TEST2 = 5 ,
LIST_GOODS = 6 ,
LAYOUT_ITEM = 8 ,
IMG_ITEMBG = 1 ,
BTN_ITEMPAY = 2 ,
NUMSTEP_TEST = 9 ,
ARMATURE_BOSS1 = 10 ,
PTL_FLOWER = 11 ,
LAB_HELLO = 12 ,
TGV_OPTION = 13 ,
ANIM_COIN = 14 ,
CKB_TEST = 15  

 }