/********************************************************************/
/*      THIS FILE IS GENERATED BY FLASHCS, DO NOT EDIT PLEASE       */
/********************************************************************/

#ifndef GAMEUIEVENT_H
#define GAMEUIEVENT_H

/** controls name */
#define s_t_btn_start "btn_start"
#define s_t_panel_game "panel_game"
#define s_t_panel_start "panel_start"
#define s_t_btn_back "btn_back"

/** all tui events defined here */
static TuiEventCallBackTable tui_event_cb_table[] = { 
	{ "panel_start_click_btn_start", tuievent_cb(GameUIController::on_event_panel_start_click_btn_start) },
	{ "panel_game_click_btn_back", tuievent_cb(GameUIController::on_event_panel_game_click_btn_back) },
};
#endif//GAMEUIEVENT_H